"""Fill the memo, evaluation page, and README measured blocks from harness JSON."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
TE = HERE / "term_extraction" / "results"
SIM = HERE / "similarity_comparison" / "results"
NOISE = HERE / "noise_degradation" / "results"


def _read(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))  # type: ignore[no-any-return]


def _table(md: str, startswith: str) -> str:
    lines = md.splitlines()
    start = next(i for i, line in enumerate(lines) if line.startswith(startswith))
    return "\n".join(line for line in lines[start:] if line.startswith("|") or line == "")


def render_memo() -> str:
    template = (HERE / "templates" / "research-memo.md").read_text(encoding="utf-8")
    te = _read(TE / "results.json")
    sim = _read(SIM / "results.json")
    noise = _read(NOISE / "results.json")
    te_md = (TE / "results.md").read_text(encoding="utf-8")
    sim_md = (SIM / "results.md").read_text(encoding="utf-8")
    noise_md = (NOISE / "results.md").read_text(encoding="utf-8")
    aware = te["polarity_aware"]
    cost = (
        f"- Term-extraction harness: {te['n_vignettes']} vignettes, no network.\n"
        f"- Similarity harness: {sim['n_patients']} simulated patients, seed {sim['seed']}.\n"
        f"- Default measure: {sim['default_measure']}.\n"
        "- Live HPO ingest time/size: unmeasured.\n"
        "- No API calls."
    )
    te_summary = (
        f"Polarity-aware F1 positive/negated/uncertain = "
        f"{aware['positive']['f1']:.3f}/"
        f"{aware['negated']['f1']:.3f}/"
        f"{aware['uncertain']['f1']:.3f}. "
        f"Naive negated F1 = {te['naive_baseline']['negated']['f1']:.3f}."
    )
    sim_summary = (
        f"Resnik top-1 = {sim['resnik']['top1']:.3f}; "
        f"Phenomizer-style top-1 = {sim['phenomizer']['top1']:.3f} "
        f"(n={sim['n_patients']})."
    )
    noise_summary = (
        f"Clean top-1 = {noise['clean_top1']:.3f}; "
        f"harsh top-1 = {noise['harsh_top1']:.3f}. "
        f"{noise['decision']}"
    )
    return (
        template.replace("{{TE_N}}", str(te["n_vignettes"]))
        .replace("{{TE_TABLE}}", _table(te_md, "| polarity"))
        .replace("{{TE_DECISION}}", str(te["decision"]))
        .replace("{{SIM_N}}", str(sim["n_patients"]))
        .replace("{{SIM_TABLE}}", _table(sim_md, "| measure"))
        .replace("{{SIM_DECISION}}", str(sim["decision"]))
        .replace("{{NOISE_TABLE}}", _table(noise_md, "| drop"))
        .replace("{{NOISE_DECISION}}", str(noise["decision"]))
        .replace("{{TE_SUMMARY}}", te_summary)
        .replace("{{SIM_SUMMARY}}", sim_summary)
        .replace("{{NOISE_SUMMARY}}", noise_summary)
        .replace("{{COST_MODEL}}", cost)
    )


def render_eval() -> str:
    return (
        "# Evaluation (Phase 0 baseline)\n\n"
        "Regenerated by `make eval` / `make research`. "
        "Expert-labeled clinic notes do not exist yet. "
        "The naive extractor is the baseline the polarity-aware system must beat.\n\n"
        + (TE / "results.md").read_text(encoding="utf-8")
        + "\n"
        + (SIM / "results.md").read_text(encoding="utf-8")
        + "\n"
        + (NOISE / "results.md").read_text(encoding="utf-8")
    )


def _replace_block(text: str, begin: str, end: str, body: str) -> str:
    start = text.index(begin) + len(begin)
    stop = text.index(end)
    return text[:start] + "\n\n" + body.strip() + "\n\n" + text[stop:]


def patch_readme() -> None:
    path = ROOT / "README.md"
    if not path.exists():
        return
    te = _read(TE / "results.json")
    sim = _read(SIM / "results.json")
    noise = _read(NOISE / "results.json")
    aware = te["polarity_aware"]
    naive = te["naive_baseline"]
    body = (
        "| System | Result | n | Notes |\n"
        "| --- | --- | --- | --- |\n"
        f"| Naive extractor (baseline) | negated F1 {naive['negated']['f1']:.3f} | "
        f"{te['n_vignettes']} | All mentions labeled positive |\n"
        f"| Polarity-aware extractor | negated F1 {aware['negated']['f1']:.3f} | "
        f"{te['n_vignettes']} | Rules + committed lexicon |\n"
        f"| Resnik ranking | top-1 {sim['resnik']['top1']:.3f} | "
        f"{sim['n_patients']} | Asymmetric mean-best IC |\n"
        f"| Phenomizer-style ranking | top-1 {sim['phenomizer']['top1']:.3f} | "
        f"{sim['n_patients']} | Symmetric Resnik |\n"
        f"| Harsh noise cell | top-1 {noise['harsh_top1']:.3f} | "
        f"{int(noise['cells']['drop_0.5_noise_2']['n'])} diseases | "
        "50% drop + 2 noise terms |\n"
    )
    path.write_text(
        _replace_block(
            path.read_text(encoding="utf-8"),
            "<!-- EVAL_TABLE_BEGIN -->",
            "<!-- EVAL_TABLE_END -->",
            body,
        ),
        encoding="utf-8",
    )


def main() -> None:
    memo_path = ROOT / "docs" / "phase-0" / "research-memo.md"
    memo_path.parent.mkdir(parents=True, exist_ok=True)
    memo_path.write_text(render_memo(), encoding="utf-8")
    (ROOT / "docs" / "EVALUATION.md").write_text(render_eval(), encoding="utf-8")
    patch_readme()
    print("wrote docs/phase-0/research-memo.md, docs/EVALUATION.md, README results block")


if __name__ == "__main__":
    main()
